affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: indikak2000/automate-openshift-deployment
  tag: eea46fdb-e01e-4726-960e-9ef4b916be90
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
initialDelaySeconds: 5
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 3000
  type: NodePort
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []
